#!/bin/bash

if (( $# < 1 )); then
    echo "Usage: $ slader <isbn>"
    exit
fi

isbn="$1"
mkdir ~/.slader 2> /dev/null

if ! python setup_isbn.py "$isbn"; then
    exit
fi

until python slader.py "$1" 2> /dev/null; do
    sleep 1 #sleep so we can ctrl-c
done


